# -*- coding: utf-8 -*-
"""data-preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8hWqvNMS2YY_Qe5KRHy8uR2P_X2m6Gc

### Load data
"""

import seaborn as sns

df = sns.load_dataset('titanic').drop(columns=['pclass', 'embarked', 'alive'])
df.head()

df.info()

import pandas as pd

# Format data for dashboard
df.columns = df.columns.str.capitalize().str.replace('_', ' ')
df.rename(columns={'Sex': 'Gender'}, inplace=True)
for col in df.select_dtypes('object').columns:
    df[col] = df[col].str.capitalize()

"""### Split the data for training and testing"""

# Partition into train and test splits
TARGET = 'Survived'
y = df[TARGET]
X = df.drop(columns=TARGET)

from sklearn.model_selection import train_test_split

numerical = X.select_dtypes(include=['number', 'boolean']).columns
categorical = X.select_dtypes(exclude=['number', 'boolean']).columns
X[categorical] = X[categorical].astype('object')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=42,
                                                    stratify=y)
train = pd.concat([X_train, y_train], axis=1)
test = pd.concat([X_test, y_test], axis=1)

"""### Clean and transform the data"""

from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

# Build pipeline
pipeline = Pipeline([
    ('preprocessor', ColumnTransformer(transformers=[
        ('cat', Pipeline([
            ('imputer', SimpleImputer(strategy='constant', fill_value='Missing')),
            ('encoder', OneHotEncoder(sparse_output=False))

        ]), categorical),
        ('num', SimpleImputer(strategy='mean'), numerical)
    ])),
    ('model', RandomForestClassifier(random_state=42))
])
pipeline.fit(X_train, y_train)


# Add predicted probabilities
test['Probability'] = pipeline.predict_proba(X_test)[:,1]
test['Target'] = test[TARGET]
test[TARGET] = test[TARGET].map({0: 'No', 1: 'Yes'})

import numpy as np

labels = []
for i, x in enumerate(np.arange(0, 101, 10)):
    if i>0:
        labels.append(f"{previous_x}% to <{x}%")
    previous_x = x
test['Binned probability'] = pd.cut(test['Probability'], len(labels),
                                    labels=labels, right=False)
test

test['Survived'].value_counts()

labels

from google.colab import files

test.to_csv('test.csv', index=False)
files.download('test.csv')

from google.colab import files
import joblib

joblib.dump(pipeline, 'model.pkl')
files.download('model.pkl')

"""### Survival rate of each passenger class"""

def status_in_class(klass, status):
    """
    Compute the number of passengers in a given passenger class
    and how many of them survived or perished.
    @param klass the given class.
    @param status either 'yes' for survived, or 'no' if perished
    @return a tuple containing the number of passengers
            and the number who survived or perished
    """

    class_count  = 0
    status_count = 0

    for srv, kls in zip(test.Survived, test.Class):
        if kls == klass:  # the class that we want?
            class_count += 1

            if srv == status:  # survived or perished in that class?
                status_count += 1

    return (class_count, status_count)

count_1st, survived_1st = status_in_class('First', 'Yes')
count_2nd, survived_2nd = status_in_class('Second', 'Yes')
count_3rd, survived_3rd = status_in_class('Third', 'Yes')

# We already have the counts in each class.
_, perished_1st = status_in_class('First', 'No')
_, perished_2nd = status_in_class('Second', 'No')
_, perished_3rd = status_in_class('Third', 'No')

total_passengers = len(test.Survived)
total_survived   = survived_1st + survived_2nd + survived_3rd
total_perished   = perished_1st + perished_2nd + perished_3rd

print(f'Out of {total_passengers} total passengers, ' +
      f'{total_survived} survived = {int(100*total_survived/total_passengers)}% ' +
      f'and {total_perished} perished = {int(100*total_perished/total_passengers)}%')
print()

pct_survived_1st = int(100*survived_1st/count_1st)
pct_survived_2nd = int(100*survived_2nd/count_2nd)
pct_survived_3rd = int(100*survived_3rd/count_3rd)

print(f'Out of {count_1st} passengers in 1st class, ' +
      f'{survived_1st} survived = {pct_survived_1st}%')
print(f'Out of {count_2nd} passengers in 2nd class, ' +
      f'{survived_2nd} survived = {pct_survived_2nd}%')
print(f'Out of {count_3rd} passengers in 3rd class, ' +
      f'{survived_3rd} survived = {pct_survived_3rd}%')